
import { Cuisine, MeatType, MeatWeight, CuisineType } from './types';

// Kept for fallback or mixed usage if needed, but primary logic will now use CUISINE_SPECIFIC_DISHES
export const POPULAR_DISHES = [
  { name: 'Butter Chicken', cuisine: 'Desi' },
  { name: 'Kung Pao Chicken', cuisine: 'Chinese' },
  { name: 'Mandi', cuisine: 'Arabian' },
  { name: 'Shepherd\'s Pie', cuisine: 'English' },
  { name: 'Biryani', cuisine: 'Desi' },
  { name: 'Beef Wellington', cuisine: 'English' },
];

export const CUISINE_SPECIFIC_DISHES: Record<CuisineType, string[]> = {
  Desi: [
    "Chicken Biryani", "Butter Chicken", "Nihari", "Mutton Karahi", "Chapli Kabab",
    "Palak Paneer", "Dal Makhani", "Chicken Tikka Masala", "Seekh Kabab", "Haleem",
    "Aloo Gobi", "Rogan Josh", "Chicken Korma", "Paya", "Samosa Chaat",
    "Beef Pulao", "Tandoori Chicken", "Malai Kofta", "Chana Masala", "Saag Paneer",
    "Shami Kabab", "Keema Aloo"
  ],
  Chinese: [
    "Kung Pao Chicken", "Sweet and Sour Chicken", "Peking Duck", "Beef and Broccoli",
    "Mapo Tofu", "Chow Mein", "Spring Rolls", "Dim Sum", "Wontons",
    "Hot and Sour Soup", "General Tso's Chicken", "Szechuan Beef", "Egg Fried Rice",
    "Dumplings", "Lo Mein", "Orange Chicken", "Sesame Chicken", "Char Siu",
    "Egg Foo Young", "Ma Po Tofu", "Honey Walnut Shrimp", "Mongolian Beef"
  ],
  Arabian: [
    "Chicken Mandi", "Lamb Kabsa", "Hummus & Pita", "Falafel", "Shawarma",
    "Shish Tawook", "Kofta Kebab", "Mansaf", "Maqluba", "Fattoush Salad",
    "Baba Ganoush", "Tabouleh", "Koshary", "Harees", "Machboos",
    "Mutabbaq", "Kibbeh", "Stuffed Grape Leaves", "Sayadieh", "Zurbian",
    "Fahsa", "Madfoon"
  ],
  English: [
    "Fish and Chips", "Shepherd's Pie", "Beef Wellington", "Sunday Roast",
    "Bangers and Mash", "Full English Breakfast", "Toad in the Hole", "Cornish Pasty",
    "Steak and Kidney Pie", "Cottage Pie", "Scotch Egg", "Roast Beef",
    "Lancashire Hotpot", "Bubble and Squeak", "Chicken Tikka Masala (UK Style)",
    "Cauliflower Cheese", "Beef Stew", "Yorkshire Pudding", "Eton Mess",
    "Sticky Toffee Pudding", "Scones", "Victoria Sponge"
  ]
};

export const MEAT_OPTIONS: { type: MeatType; label: string; icon: string }[] = [
  { type: 'Chicken', label: 'Chicken', icon: '🍗' },
  { type: 'Mutton', label: 'Mutton', icon: '🥩' },
  { type: 'Beef', label: 'Beef', icon: '🍖' },
];

export const CUISINE_OPTIONS: { type: CuisineType; label: string; icon: string }[] = [
  { type: 'Desi', label: 'Desi', icon: '🥘' },
  { type: 'Chinese', label: 'Chinese', icon: '🥢' },
  { type: 'Arabian', label: 'Arabian', icon: '🌯' },
  { type: 'English', label: 'English', icon: '🍽️' },
];

export const WEIGHT_OPTIONS: { value: MeatWeight; label: string }[] = [
  { value: '0.5kg', label: '0.5 kg' },
  { value: '1kg', label: '1.0 kg' },
  { value: '1.5kg', label: '1.5 kg' },
  { value: '2kg', label: '2.0 kg' },
];

export const UI_TEXT = {
  en: {
    appTitle: 'Desi Dastarkhwan',
    subtitle: 'A Global Kitchen: Desi, Arabian, Chinese & English',
    searchPlaceholder: 'Search for a dish...',
    generateButton: 'Find Recipe',
    ingredients: 'Ingredients',
    instructions: 'Instructions',
    cookingTime: 'Cooking Time',
    prepTime: 'Prep Time',
    totalTime: 'Total Time',
    servings: 'Servings',
    difficulty: 'Difficulty',
    nutrition: 'Nutrition Facts',
    tips: "Chef's Tips",
    generating: 'Chefs are cooking up your recipe...',
    generatingImage: 'Plating your dish...',
    selectCuisine: 'Or explore by cuisine',
    welcome: 'Welcome! Pick your meat & start cooking.',
    history: 'History & Origin',
    back: 'Back to Search',
    tryThese: 'Top dishes in this category:',
    selectMeat: 'Select Main Ingredient',
    selectWeight: 'Quantity of Meat',
    selectCuisineLabel: 'Choose Cuisine Style',
    any: 'Any / Veg',
    originalVersion: 'Original Recipe',
    healthyVersion: 'Healthy Twist',
    macros: 'Macros',
    carbs: 'Carbs',
    fats: 'Fats',
    protein: 'Protein',
    playAudio: 'Play Step',
    servingSize: 'Serving Size',
    perServing: 'Per Serving',
    totalRecipe: 'Total Recipe',
    adjustServing: 'Adjust Portion',
    calories: 'Calories',
    baseRecipeFor: 'Recipe based on',
    playFullRecipe: 'Listen to Full Recipe',
    pauseAudio: 'Pause Audio',
    resumeAudio: 'Resume Audio',
    stopAudio: 'Stop Audio',
    listening: 'Listening...',
    lowCarbMode: 'Low Carb / Keto Mode',
    lowCarbDesc: 'High protein, minimal carbs',
    standardMode: 'Standard Mode',
    share: 'Share',
    shareWhatsApp: 'WhatsApp',
    shareFB: 'Facebook',
    copyLink: 'Copy Link',
    copied: 'Copied!',
  },
  ur: {
    appTitle: 'دیسی دسترخوان',
    subtitle: 'عالمی ذائقے: دیسی، عربی، چینی اور انگریزی',
    searchPlaceholder: 'کوئی ڈش تلاش کریں...',
    generateButton: 'ترکیب تلاش کریں',
    ingredients: 'اجزاء',
    instructions: 'ہدایات',
    cookingTime: 'پکانے کا وقت',
    prepTime: 'تیاری کا وقت',
    totalTime: 'کل وقت',
    servings: 'افراد',
    difficulty: 'مشکل',
    nutrition: 'غذائیت کی تفصیلات',
    tips: 'شیف کے مشورے',
    generating: 'باورچی آپ کی ترکیب تیار کر رہے ہیں...',
    generatingImage: 'کھانا پیش کیا جا رہا ہے...',
    selectCuisine: 'یا کھانوں کے لحاظ سے دریافت کریں',
    welcome: 'خوش آمدید! گوشت کا انتخاب کریں اور پکانا شروع کریں۔',
    history: 'تاریخ اور پس منظر',
    back: 'واپس تلاش کریں',
    tryThese: 'اس زمرے کے مشہور کھانے:',
    selectMeat: 'گوشت کا انتخاب کریں',
    selectWeight: 'گوشت کی مقدار',
    selectCuisineLabel: 'کھانے کا انداز',
    any: 'کوئی بھی / سبزی',
    originalVersion: 'اصل نسخہ',
    healthyVersion: 'صحت بخش نسخہ',
    macros: 'میکروز',
    carbs: 'کاربوہائیڈریٹ',
    fats: 'چکنائی',
    protein: 'پروٹین',
    playAudio: 'سنیں',
    servingSize: 'سرونگ کا سائز',
    perServing: 'فی سرونگ',
    totalRecipe: 'مکمل ترکیب',
    adjustServing: 'مقدار تبدیل کریں',
    calories: 'کیلوریز',
    baseRecipeFor: 'نسخہ کی بنیاد',
    playFullRecipe: 'پوری ترکیب سنیں',
    pauseAudio: 'روک دیں',
    resumeAudio: 'جاری رکھیں',
    stopAudio: 'بند کریں',
    listening: 'چل رہا ہے...',
    lowCarbMode: 'لو کارب / کیٹو موڈ',
    lowCarbDesc: 'زیادہ پروٹین، کم کاربوہائیڈریٹ',
    standardMode: 'عام موڈ',
    share: 'شیئر کریں',
    shareWhatsApp: 'واٹس ایپ',
    shareFB: 'فیس بک',
    copyLink: 'لنک کاپی کریں',
    copied: 'کاپی ہو گیا!',
  },
  roman: {
    appTitle: 'Desi Dastarkhwan',
    subtitle: 'Global Zaiqay: Desi, Arabian, Chinese aur English',
    searchPlaceholder: 'Koi dish talash karein...',
    generateButton: 'Recipe Talash Karein',
    ingredients: 'Ajza',
    instructions: 'Tarkeeb',
    cookingTime: 'Pakane ka Waqt',
    prepTime: 'Tayari ka Waqt',
    totalTime: 'Kul Waqt',
    servings: 'Afraad',
    difficulty: 'Mushkil',
    nutrition: 'Ghizaiyat',
    tips: 'Chef ke Mashwaray',
    generating: 'Bawarchi aap ki recipe tayar kar rahay hain...',
    generatingImage: 'Khana pesh kiya ja raha hai...',
    selectCuisine: 'Ya cuisine ke hisaab se dhundain',
    welcome: 'Khush Amdeed! Gosht chunein aur pakana shuru karein.',
    history: 'Tareekh aur Pas Manzar',
    back: 'Wapis Talash Karein',
    tryThese: 'Is category ke mashhoor khanay:',
    selectMeat: 'Gosht ka intekhab karein',
    selectWeight: 'Gosht ki Miqdar',
    selectCuisineLabel: 'Khane ka Andaaz',
    any: 'Koi bhi / Sabzi',
    originalVersion: 'Asli Recipe',
    healthyVersion: 'Healthy Version',
    macros: 'Macros',
    carbs: 'Carbs',
    fats: 'Fats',
    protein: 'Protein',
    playAudio: 'Sunain',
    servingSize: 'Serving Size',
    perServing: 'Per Serving',
    totalRecipe: 'Puri Recipe',
    adjustServing: 'Miqdar Badlain',
    calories: 'Calories',
    baseRecipeFor: 'Recipe ki buniyaad',
    playFullRecipe: 'Puri Recipe Sunain',
    pauseAudio: 'Rokain',
    resumeAudio: 'Jaari Rakhain',
    stopAudio: 'Band Karein',
    listening: 'Sun raha hun...',
    lowCarbMode: 'Low Carb / Keto Mode',
    lowCarbDesc: 'Ziada protein, kam carbs',
    standardMode: 'Aam Mode',
    share: 'Share',
    shareWhatsApp: 'WhatsApp',
    shareFB: 'Facebook',
    copyLink: 'Link Copy Karein',
    copied: 'Copy hogaya!',
  }
};
